version: '3.1'
services:
  nginx:
    image: nginx:1.25.1-alpine
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./cms:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  cms:
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./cms:/app
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=bitrix
      - MYSQL_DATABASE=bitrix
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=bitrix
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
