version: '3.1'
services:
  nginx:
    image: nginx:1.25.1-alpine
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./cms:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  cms:
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./cms:/app
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=opencart
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=opencart
      - MYSQL_PASSWORD=opencart